# Generated by Django 3.1.1 on 2022-11-01 07:47

import course.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221101_1547'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '课程种类表', 'verbose_name_plural': '课程种类表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterField(
            model_name='course',
            name='createDatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 15, 47, 30, 499932), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fileName',
            field=models.FileField(upload_to=course.models.save_file, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='imgName',
            field=models.ImageField(upload_to=course.models.save_image, verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '收费'), (1, '免费')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='课程介绍'),
        ),
        migrations.AlterField(
            model_name='course',
            name='userBuyer',
            field=models.ManyToManyField(blank=True, related_name='userBuyer_set', to='user.User', verbose_name='购买用户'),
        ),
        migrations.AlterField(
            model_name='course',
            name='userShoppingcart',
            field=models.ManyToManyField(blank=True, related_name='userShoppingcart_set', to='user.User', verbose_name='加入购物车的用户'),
        ),
    ]
